# Generated by Django 4.0.8 on 2024-02-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnglishDictionary',
        ),
    ]
