# Generated by Django 4.0.8 on 2024-02-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0002_delete_englishdictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlist',
            name='founded_words',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
