# Generated by Django 4.0.8 on 2024-02-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0004_alter_matchlist_founded_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlist',
            name='last_latter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
