# Generated by Django 4.0.8 on 2024-02-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0005_matchlist_last_latter'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlist',
            name='last_word',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
