# Generated by Django 4.0.8 on 2024-02-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0006_matchlist_last_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlist',
            name='founded_words2',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='founded_words',
            field=models.CharField(blank=True, default='1', max_length=10000, null=True),
        ),
    ]
