# Generated by Django 4.0.8 on 2024-02-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0007_matchlist_founded_words2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchlist',
            old_name='founded_words2',
            new_name='founded_words_save',
        ),
    ]
