# Generated by Django 4.0.8 on 2024-02-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0009_alter_matchlist_founded_words_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlist',
            name='uptade_queue',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
